pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                script {
                    echo "installing...."
                    sh 'npm install'
                }
            }
        }
        stage("Build") {
            steps {
                script {
                    echo "building the docker image..."
                    dir('app') {
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                            sh "docker build -t analystrusso/jenkins-exercise:1.0 ."
                            sh 'echo $PASS | docker login -u $USER --password-stdin'
                            sh "docker push analystrusso/jenkins-exercise:1.0"
                    }
                }
            }
        }
    }
        stage("Test") {
            steps {
                script {
                    echo "testing...."
                    sh 'npm test'
                }
            }
        }

        stage("Start") {
            steps {
                script {
                    echo "starting...."
                    sh 'npm start'
                }
            }
        }
    }
}